#!/bin/bash

ROOT=$(dirname $(dirname $0))

cd $ROOT

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

if [ ! -d "$VENV_NAME" ]; then
    if [ -z "$VENV_PYTHON" ]; then
        VENV_PYTHON=$(command -v python3)
    fi
    "$VENV_PYTHON" -m venv "$VENV_NAME"
fi
. "$VENV_NAME/bin/activate"

python -m pip install -r requirements.txt
